# Database Configuration
spring.application.name=order_service
spring.datasource.url=jdbc:postgresql://localhost:15432/orders_db
spring.datasource.username=admin
spring.datasource.password=syntax
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.com.order_service.config=INFO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
