server:
  port: 8080  # Application will run on port 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orders_db
    username: admin
    password: syntax
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.order_service: DEBUG
