server:
  port: 8080  # Application will run on port 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: order_user
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev  # Activate the 'dev' profile

logging:
  level:
    root: INFO
    com.order_service: DEBUG